
* Summary

  This is a hobby project to make a turn-based towerdefense game.
  This will be a more asynchronous game, where you set up the towers
  then hit "go".

  The "story" if I ever get around to making it, will be something
  sci-fi-ish where the player is a deep-space miner and goes into
  suspended animation for long periods of time, waking up to shore up
  the defenses.

* Todo
** DONE foundation crap
** DONE get a grid for the playing board
** simulation
*** refinery
    basic resource-gathering structure
* Implementation
** lisp for simulations
*** basic 2-stage plan/act cycle for each game piece
** sdl for rendering
*** fixed grid square size
    I always get bogged down in making everything dynamic based on
    window size, just keep it fixed for now.
*** animation queue
    want to make some have animations that must run their course
    before the next turn starts.  Did something similar in sandbox,
    but those were modelled like any other actor in the system, and I
    think these should be separate to prevent snowballing.
**** simple list of objects on the renderer 
     They keep track of their age, and wait for all of them to die
     before moving on to the next step in the simulation.
